//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1demoo.
        /// </summary>
        public static string _1demoo {
            get {
                return ResourceManager.GetString("1demoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản giao dịch.
        /// </summary>
        public static string AccountTransactions {
            get {
                return ResourceManager.GetString("AccountTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay Về.
        /// </summary>
        public static string Admin_Back {
            get {
                return ResourceManager.GetString("Admin_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Ảnh.
        /// </summary>
        public static string Admin_ChooseImage {
            get {
                return ResourceManager.GetString("Admin_ChooseImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Mới.
        /// </summary>
        public static string Admin_Create {
            get {
                return ResourceManager.GetString("Admin_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh Sửa.
        /// </summary>
        public static string Admin_Edit {
            get {
                return ResourceManager.GetString("Admin_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làm Lại.
        /// </summary>
        public static string Admin_Reset {
            get {
                return ResourceManager.GetString("Admin_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Admin_Save {
            get {
                return ResourceManager.GetString("Admin_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu Và Tiếp Tục Chỉnh Sửa.
        /// </summary>
        public static string Admin_SaveContinue {
            get {
                return ResourceManager.GetString("Admin_SaveContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quyền lợi hợp tác.
        /// </summary>
        public static string BenefitsOfCooperation {
            get {
                return ResourceManager.GetString("BenefitsOfCooperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh Mục.
        /// </summary>
        public static string BlogCategoryId {
            get {
                return ResourceManager.GetString("BlogCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình Ảnh.
        /// </summary>
        public static string BlogImage {
            get {
                return ResourceManager.GetString("BlogImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đặt Tour Trực Tuyến.
        /// </summary>
        public static string BookingTourOnline {
            get {
                return ResourceManager.GetString("BookingTourOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPDKKD: .
        /// </summary>
        public static string BusinessLicenseRegistration {
            get {
                return ResourceManager.GetString("BusinessLicenseRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4201191802 Do Sở KHĐT Tỉnh KH cấp ngày 14/06/2010.
        /// </summary>
        public static string BusinessLicenseRegistrationContent {
            get {
                return ResourceManager.GetString("BusinessLicenseRegistrationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ĐỐI TÁC LỮ HÀNH &amp; KHÁCH SẠN.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tư Vấn Tour &amp; Sự Kiện.
        /// </summary>
        public static string ConsultingTourEvent {
            get {
                return ResourceManager.GetString("ConsultingTourEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên Hệ.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội Dung.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp Tác.
        /// </summary>
        public static string Cooporation {
            get {
                return ResourceManager.GetString("Cooporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chăm Sóc Khách Hàng.
        /// </summary>
        public static string CustomerService {
            get {
                return ResourceManager.GetString("CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Tổ Chức Hàng Ngày.
        /// </summary>
        public static string DailyTour {
            get {
                return ResourceManager.GetString("DailyTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô Tả.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh Sửa Seo.
        /// </summary>
        public static string EditSeo {
            get {
                return ResourceManager.GetString("EditSeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAN LABIXA.
        /// </summary>
        public static string FanLabixa {
            get {
                return ResourceManager.GetString("FanLabixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trụ sở: .
        /// </summary>
        public static string HeadQuarter {
            get {
                return ResourceManager.GetString("HeadQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 38b Trần Phú Vĩnh Nguyên Nha Trang.
        /// </summary>
        public static string HeadQuarterAddress {
            get {
                return ResourceManager.GetString("HeadQuarterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ Giúp.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang Chủ.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới Thiệu.
        /// </summary>
        public static string Introduce {
            get {
                return ResourceManager.GetString("Introduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu mô hình .
        /// </summary>
        public static string IntroduceModel {
            get {
                return ResourceManager.GetString("IntroduceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển Thị.
        /// </summary>
        public static string IsAvailable {
            get {
                return ResourceManager.GetString("IsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bè Labixa.
        /// </summary>
        public static string LabixaBoat {
            get {
                return ResourceManager.GetString("LabixaBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ Meta Mô Tả.
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ Meta Từ Khóa.
        /// </summary>
        public static string MetaKeyWords {
            get {
                return ResourceManager.GetString("MetaKeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thẻ Meta Trang.
        /// </summary>
        public static string MetaTitle {
            get {
                return ResourceManager.GetString("MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin Tức.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÁO CHÍ - TRUYỀN HÌNH &amp; LABIXA.
        /// </summary>
        public static string NewsTVLabixa {
            get {
                return ResourceManager.GetString("NewsTVLabixa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPGD: .
        /// </summary>
        public static string OfficeTransactions {
            get {
                return ResourceManager.GetString("OfficeTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09 Lê Quý Đôn, Phước Tiến, Nha Trang.
        /// </summary>
        public static string OfficeTransactionsAddress {
            get {
                return ResourceManager.GetString("OfficeTransactionsAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XEM THÊM TIN TỨC.
        /// </summary>
        public static string otherNews {
            get {
                return ResourceManager.GetString("otherNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CÁC DỊCH VỤ KHÁC TẠI LABIXA.
        /// </summary>
        public static string OtherService {
            get {
                return ResourceManager.GetString("OtherService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem Các Tour Hấp Dẫn Khác.
        /// </summary>
        public static string OtherTour {
            get {
                return ResourceManager.GetString("OtherTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn thanh toán.
        /// </summary>
        public static string PaymentGuide {
            get {
                return ResourceManager.GetString("PaymentGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bảng giá thẻ Vinpearl Land a.
        /// </summary>
        public static string PriceVinpearlLand {
            get {
                return ResourceManager.GetString("PriceVinpearlLand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khuyến Mãi.
        /// </summary>
        public static string Promotion {
            get {
                return ResourceManager.GetString("Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỏi Đáp.
        /// </summary>
        public static string QA {
            get {
                return ResourceManager.GetString("QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuyển Dụng.
        /// </summary>
        public static string Recruitment {
            get {
                return ResourceManager.GetString("Recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy định Đổi trả -  Hoàn Tiền.
        /// </summary>
        public static string RegulationChangesPaidRefund {
            get {
                return ResourceManager.GetString("RegulationChangesPaidRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quy định thảo luận.
        /// </summary>
        public static string Regulationsdiscussed {
            get {
                return ResourceManager.GetString("Regulationsdiscussed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dịch Vụ.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn mua hàng.
        /// </summary>
        public static string ShoppingGuide {
            get {
                return ResourceManager.GetString("ShoppingGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Rút Gọn.
        /// </summary>
        public static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hỗ trợ trực tuyến.
        /// </summary>
        public static string SupportOnline {
            get {
                return ResourceManager.GetString("SupportOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu Đề.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bè Du Lịch Labixa - Ngôi Nhà Giữa Biển.
        /// </summary>
        public static string TitleLabixaBoat {
            get {
                return ResourceManager.GetString("TitleLabixaBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Dịch Vụ Labixa.
        /// </summary>
        public static string TopService {
            get {
                return ResourceManager.GetString("TopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour.
        /// </summary>
        public static string Tour {
            get {
                return ResourceManager.GetString("Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIDEO.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labixa là gì?.
        /// </summary>
        public static string WhatIsLabixa {
            get {
                return ResourceManager.GetString("WhatIsLabixa", resourceCulture);
            }
        }
    }
}
